#!/usr/bin/env bash
# As always: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

branch="$(git rev-parse --abbrev-ref HEAD)"

url="https://github.com/tibiiii/playground/compare/master...$branch?quick_pull=1"

# if [[ "$branch" =~ ^SHAP-[0-9]*_.*$ ]]; then
    ticket_id="${branch%%_*}"
    TEMPLATE_FILE="./.github/pull_request_template.md"
    TEMP_TEMPLATE_FILE="./.github/pull_request_template.md.tmp"
    sed 's,<!--- Jira url -->,https://shapr3d.atlassian.net/browse/${ticket_id},g' <"$TEMPLATE_FILE" >"$TEMP_TEMPLATE_FILE"
    url="$url&body="$(jq -sRr @uri "$TEMP_TEMPLATE_FILE")"&title=[$ticket_id]"
    rm $TEMP_TEMPLATE_FILE
# fi

open "$url"
