name: Merge back

on:
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(fromJson('["refs/heads/master", "refs/heads/release"]'), github.ref) }}    

jobs:
  merge_back:
    if: github.event_name == 'schedule' || github.event.ref == 'refs/heads/master' || github.event.ref == 'refs/heads/retail_demo' || startsWith(github.event.ref, 'refs/heads/release')
    runs-on: [ubuntu-latest]
    timeout-minutes: 30
    env:
      CLEAN: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.clean }}
      FORCE_CLEAN: ${{ secrets.FORCE_CLEAN }}
    steps:
      - name: List inputs
        run: |
          echo '${{ toJSON(github.event.inputs) }}'
      - name: Hostname
        run: |
          echo "Running on: $(hostname)"
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          clean: ${{ env.CLEAN }}
          fetch-depth: 0
          lfs: true
          persist-credentials: true
      - name: Clean
        if: ${{ env.CLEAN == 'true' }}
        run: |
          echo "clean"
      - name: Run merge back script
        env:
          GITHUB_TOKEN: ${{ secrets.SHAPR_GITHUB_TOKEN }}
        run: |
          ./.github/scripts/merge_back.sh
