name: Merge back

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: [ubuntu-latest]
    timeout-minutes: 30
    steps:
      - name: Step 1
        run: |
          echo "step 1"
  job2:
    runs-on: [ubuntu-latest]
    timeout-minutes: 30
    steps:
      - name: Step 1
        run: |
          echo "step 1"

  job3:
    runs-on: [ubuntu-latest]
    timeout-minutes: 30
    if: ${{ always() }}
    needs: [job1, job2]
    steps:
      - name: Step 1
        run: |
          echo "step 1"
          echo "job1 result:"
          echo ${{ needs.job1.result }}

          echo "job2 result:"
          echo ${{ needs.job2.result }}
